name: Build2

on:
  push:
    branches:
    - master

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run : wget https://github.com/HeaTTheatR/KivyMD-data/raw/master/install-kivy-buildozer-dependencies.sh

      - run : chmod +x install-kivy-buildozer-dependencies.sh
      - run : ./install-kivy-buildozer-dependencies.sh

      - name: Run build 
        run : echo y | buildozer -v android debug